version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - apt-get install -y unzip
  build:
    commands:
      - echo build started `date`
      - zip hello.zip ./index.html
artifacts:
  files:
    - appspec.yml
    - index.html
    - scripts/install_dependencies
    - scripts/start_server

